### ISSUE TITLE
[Feature Request] 增加过滤已看完视频功能

### ISSUE THREAD

**Issue by yunchong-song** [Fatpandac/Raycast-Bilibili#2]
场景：在使用此插件的 `Show Dynamic Feed` 功能的时候，通常会有些视频是已经看完了的，不希望他们出现在列表里，会造成用户“回忆我是否看过这个视频“ 的负担

建议：希望在`Show Dynamic Feed` 功能的 `List View` 的右上角增加一个filter，用于过滤用户尚未观看的视频，判定标准可以为用户观看进度超过90%，或被b站标记为“已看完”

其他：至于实现和PR，没有开发过Raycast插件，对TS和爬虫也不熟悉，所以只能提供些建议了。这个插件还是非常棒的，RSSHub提供的Bilibili路由失效后，我每天都用这个插件看刷b站时间线，感谢作者

**Comment by Fatpandac** [comment]
已经在 [451d1be](https://github.com/Fatpandac/Raycast-Bilibili/commit/451d1bebf11915c72b19672f628dfb51d14e72cc) 实现
bilibili 没有判断视频是否看过的相关字段，这里实现采用的是判断对应视频上一次观看的时间点不为零
