### ISSUE TITLE
[Feature Request] 增加“标记为看过”功能

### ISSUE THREAD

**Issue by yunchong-song** [Fatpandac/Raycast-Bilibili#3]
感谢作者对这个项目的维护，这个插件确实用起来非常舒服

- 需求：对于个人订阅视频中的某些条目，可能看到标题/封面就不想看了，目前如果想让他消失在列表里只能点进视频并播放几秒，才能让他被过滤掉。

- 描述：如果能提供一个 `Action` ，让用户手动标记这类不想看的视频为“已看完”或许会更好，这类似在RSS中的操作；更进一步，也许可以提供“全部标记为已看完”的功能，也就是将订阅列表清空

- 可能的方案
  - 如果哔哩哔哩没有提供类似“标记为已看完”的API，或许可以在Raycast中存储这样的状态表
  - 如果有这样的API，直接调用即可，也可以让Raycast中的操作同步到哔哩哔哩的后端，更优雅一些

**Comment by Fatpandac** [comment]
多谢夸奖

该功能已经在 [78441a8](https://github.com/Fatpandac/Raycast-Bilibili/commit/78441a895d7fce80e736f9835d9c29f30ef191b3) 实现，通过为视频添加一秒钟观看时间记录实现，同样这个记录会同步到 B站 你可以在观看历史里找到对应视频。
