### ISSUE TITLE
[Bug] 视频完全看完以后反而会被标记为未看完视频

### ISSUE THREAD

**Issue by yunchong-song** [Fatpandac/Raycast-Bilibili#4]
- 在 `Unwatched Videos` 中打开一个视频，假设视频时长为 `T`，发现仅在观看进度为 `(0, T)` 的时候，该视频会在列表中被过滤掉，而进度为 `0` 或 `T`（即完全看完），都会重新出现在 `Unwatched Videos` 列表里
- Raycast和商店插件版本均为最新

**Comment by Fatpandac** [comment]
这个情况我确实没有考虑到，这种情况的解决办法应该只能是在本地也做一次保存了，毕竟我没有找到 bilibili 记录看过的字段在哪一个接口，直接去查观看记录也不太实际

在 [2a6bcce4](https://github.com/Fatpandac/Raycast-Bilibili/commit/2a6bcce41f3e25888574c357b9df1a06673fec2b) 尝试修复，是否可行需要观察一段时间

Raycast 商店插件版本 是延后的，因为提交到商店需要官方 review PR 需要时间，我一般会在新功能稳定后才会同步到 Raycast 商店

**Comment by yunchong-song** [comment]
不知道你是否看到过这个项目：[SocialSisterYi/bilibili-API-collect: 哔哩哔哩-API收集整理【不断更新中....】](https://github.com/SocialSisterYi/bilibili-API-collect/tree/master)，我发现这个repo整理了历史记录相关的API（[bilibili-API-collect/docs/history&toview/history.md at master · SocialSisterYi/bilibili-API-collect](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/history&toview/history.md#获取视频观看历史记录_web端旧版)），其中包含有历史记录列表，不知道是否可用

**Comment by Fatpandac** [comment]
这里的历史记录是全部观看的历史记录，不仅仅是针对你订阅的内容，如果要从这里面找可能会浪费很多时间

**Comment by yunchong-song** [comment]
你好，请问相关改动是还没有在商店更新吗？我查看Raycast的GitHub好像也没看到相关的活跃PR？

**Comment by Fatpandac** [comment]
> 你好，请问相关改动是还没有在商店更新吗？我查看Raycast的GitHub好像也没看到相关的活跃PR？

我等下提交，忘记了😂

**Comment by Fatpandac** [comment]
@realCrush 现在已经合并到官方仓库并发布到商店了https://github.com/raycast/extensions/pull/9603

**Comment by yunchong-song** [comment]
非常感谢
